import test from 'node:test';
import assert from 'node:assert/strict';
import {firstDiveChoices,renderFirstDiveExcerpt,replaceFirstDiveSection,publishFirstDiveExcerpt,firstDiveExcerptIsCurrent,FIRST_DIVE_TARGET,FIRST_DIVE_MARKER} from '../src/helpscout-beginner-first-dive.mjs';
const checkedAt='2026-10-02T21:00:00.000Z',expiresAt='2026-10-04T09:00:00.000Z';
const event=(id,title,kind='shore',date='2026-10-09')=>({id,title,kind,startDate:date,time:'09:00',startInstant:date+'T00:00:00Z',availability:'check_availability',notes:[],bookingUrl:'https://www.abyss.com.au/charters/'+(kind==='shore'?'guided-shore-dives':'boat-dives')+'?q='+Buffer.from('part_number='+title+'&open_cart_id='+id).toString('base64')});
const fixture=()=>({source:'https://www.abyss.com.au/beginner-diver-widget',checkedAt,expiresAt,events:[event('1','Oak Park Dive'),event('2','Bare Island Dive','shore','2026-10-04'),event('3','Henry Head Boat Dive','boat','2026-10-10')]});
const article=()=>({...FIRST_DIVE_TARGET,status:'published',hasDraft:false,slug:'first-guided-dive-after-certification-support',keywords:['existing'],text:'<p>Preserved before</p><h2>Which dive should I book first?</h2><p>Old site-only answer.</p><h2>Can I join without a buddy?</h2><p>Preserve all buddy guidance.</p>'});
function mock(a=article()){
 let current=structuredClone(a),puts=0;
 return {request:async(method,url,body)=>{if(url.startsWith('/collections/'))return {collection:{id:FIRST_DIVE_TARGET.collectionId,siteId:'5d0ed4d02c7d3a6ebd2268ed',visibility:'private'}};if(method==='GET')return {article:structuredClone(current)};assert.equal(method,'PUT');assert.deepEqual(Object.keys(body),['text']);current.text=body.text;puts++;},get:()=>current,puts:()=>puts};
}
test('two default shore choices ranked Sunday first and a separate boat option',()=>{const x=firstDiveChoices(fixture());assert.deepEqual(x.primary.map(y=>y.site.key),['bare','oak']);assert.equal(x.boat.site.key,'henry');});
test('uses actual dates and exact links, not fixed example dates',()=>{const s=fixture(),html=renderFirstDiveExcerpt(s);assert.match(html,/Friday,? 9 October 2026/);assert.match(html,/Sunday,? 4 October 2026/);assert.ok(html.includes(s.events[0].bookingUrl));assert.ok(html.includes('Divemaster explains the entry'));});
test('expired recommendations do not contain dated booking cards',()=>{const s=fixture(),now=expiresAt;assert.equal(firstDiveChoices(s,{now}).primary.length,0);assert.ok(!renderFirstDiveExcerpt(s,{now}).includes('First choice:'));});
test('future check rejected',()=>assert.throws(()=>firstDiveChoices(fixture(),{now:'2026-10-01T00:00:00Z'})));
test('overlong validity rejected',()=>{const s=fixture();s.expiresAt='2026-11-01T00:00:00Z';assert.throws(()=>firstDiveChoices(s));});
test('fully booked or unknown availability never promoted',()=>{const s=fixture();s.events[0].availability='fully_booked';s.events[1].availability='unknown';assert.deepEqual(firstDiveChoices(s).primary.map(x=>x.site.key),['henry']);});
test('night, confident-only and unguided outings excluded',()=>{const s=fixture();s.events[0].title='Oak Park Night Dive';s.events[1].notes=['For confident divers'];s.events[2].notes=['unguided'];assert.equal(firstDiveChoices(s).primary.length,0);});
test('wrong product, host or credentials cannot be recommended',()=>{for(const url of ['https://evil.test/charters/guided-shore-dives?q=x','https://www.abyss.com.au/charters/tech-boat-dives?q=x','https://x@www.abyss.com.au/charters/guided-shore-dives?q=x']){const s=fixture();s.events=[{...s.events[0],bookingUrl:url}];assert.equal(firstDiveChoices(s).primary.length,0);}});
test('past starts and dates excluded',()=>{const s=fixture();s.events[0].startInstant=checkedAt;s.events[1].startDate='2026-10-01';assert.deepEqual(firstDiveChoices(s).primary.map(x=>x.site.key),['henry']);});
test('advance-booking date preferred over same-day for same site',()=>{const s=fixture();s.events.unshift({...event('4','Oak Park Dive','shore','2026-10-03'),startInstant:'2026-10-02T23:00:00Z'});assert.equal(firstDiveChoices(s).primary.find(x=>x.site.key==='oak').event.id,'1');});
test('beyond 42-day window not promoted',()=>{const s=fixture();s.events[0].startDate='2027-02-01';assert.equal(firstDiveChoices(s).primary[0].site.key,'bare');});
test('no manufactured option when no matching events',()=>{const s=fixture();s.events=[];assert.match(renderFirstDiveExcerpt(s),/No current dated recommendation/);});
test('only first FAQ section is replaced',()=>{const old=article().text,next=replaceFirstDiveSection(old,renderFirstDiveExcerpt(fixture()));assert.ok(next.startsWith('<p>Preserved before</p>'));assert.ok(next.endsWith('<h2>Can I join without a buddy?</h2><p>Preserve all buddy guidance.</p>'));assert.equal(next.split(FIRST_DIVE_MARKER).length,2);});
test('missing or duplicate target heading fails closed',()=>{assert.throws(()=>replaceFirstDiveSection('no heading','x'));assert.throws(()=>replaceFirstDiveSection(article().text+article().text,'x'));});
test('same excerpt replaces cleanly rather than accumulating copies',()=>{const x=renderFirstDiveExcerpt(fixture()),once=replaceFirstDiveSection(article().text,x);assert.equal(replaceFirstDiveSection(once,x),once);});
test('publish preserves metadata, updates one body, verifies readback',async()=>{const m=mock(),r=await publishFirstDiveExcerpt({request:m.request,snapshot:fixture()});assert.equal(r.status,'updated-and-verified');assert.equal(m.puts(),1);assert.deepEqual(m.get().keywords,['existing']);assert.equal(m.get().status,'published');});
test('existing draft is not overwritten',async()=>{const m=mock({...article(),hasDraft:true});await assert.rejects(()=>publishFirstDiveExcerpt({request:m.request,snapshot:fixture()}));assert.equal(m.puts(),0);});
test('current check matches the canonical snapshot timestamp',async()=>{const m=mock();assert.equal(await firstDiveExcerptIsCurrent(m.request,{text:'Checked (ISO): '+checkedAt}),false);await publishFirstDiveExcerpt({request:m.request,snapshot:fixture()});assert.equal(await firstDiveExcerptIsCurrent(m.request,{text:'Checked (ISO): '+checkedAt}),true);assert.equal(await firstDiveExcerptIsCurrent(m.request,{text:'Checked (ISO): 2026-10-02T22:00:00Z'}),false);});
