import test from 'node:test';import assert from 'node:assert/strict';import {DateTime} from 'luxon';
import {buildTravelSnapshot,renderTravelSnapshot,updateTravelSnapshot,TITLE,SOURCE_URL} from '../src/helpscout-travel.mjs';
const at=DateTime.fromISO('2026-09-30T13:20:00',{zone:'Australia/Sydney'});
const row={startDate:'26 Jun 2027',endDate:'08 Jul 2027',name:'Galapagos Islands Liveaboard 2027',available:'0',maxPlaces:'16',price:'$0.00',bookingUrl:'https://www.abyss.com.au/trips/galapagos-islands-2027?q=cGFydF9udW1iZXI9R2FsYXBhZ29zIElzbGFuZHMgTGl2ZWFib2FyZCAyMDI3JmRhdGU9Jm9wZW5fY2FydF9pZD02NjU0Nzg0Nw==',description:'Galapagos expedition'};
test('September abbreviation matches the actual travel feed',()=>{const s=buildTravelSnapshot([{...row,startDate:'18 Sep 2027',endDate:'25 Sep 2027'}],at);assert.equal(s.trips[0].startDate,'2027-09-18');assert.equal(s.trips[0].endDate,'2027-09-25')});
test('zero price is unknown and zero seats are sold out',()=>{const s=buildTravelSnapshot([row],at);assert.equal(s.trips[0].listedPriceAud,null);assert.equal(s.trips[0].available,0);const h=renderTravelSnapshot(s);assert.match(h,/Sold out at the check time/);assert.match(h,/Price: ask Abyss/);assert.doesNotMatch(h,/AUD \$0/)});
test('start and return dates remain separate across year boundary',()=>{const s=buildTravelSnapshot([{...row,startDate:'26 Dec 2026',endDate:'02 Jan 2027',available:'5',price:'$3,895.00'}],at);assert.equal(s.trips[0].startDate,'2026-12-26');assert.equal(s.trips[0].endDate,'2027-01-02');assert.equal(s.trips[0].listedPriceAud,3895);assert.equal(s.trips[0].bookingUrl,row.bookingUrl)});
test('bad date, missing counts, impossible capacity and unsafe link fail closed',()=>{for(const change of [{startDate:'31 Feb 2027'},{endDate:'01 Jun 2027'},{available:''},{available:'17'},{bookingUrl:'https://example.com/trips/galapagos?q=x'}])assert.throws(()=>buildTravelSnapshot([{...row,...change}],at))});
test('identical rows deduplicate; conflicting rows fail',()=>{assert.equal(buildTravelSnapshot([row,row],at).trips.length,1);assert.throws(()=>buildTravelSnapshot([row,{...row,available:'1'}],at),/Conflicting/)});
test('empty source never replaces last-known-good inventory',()=>assert.throws(()=>buildTravelSnapshot([],at),/previous snapshot/));
test('Sydney timestamps use daylight saving when applicable',()=>{const s=buildTravelSnapshot([row],DateTime.fromISO('2026-10-05T08:00:00',{zone:'Australia/Sydney'}));assert.match(s.checkedAt,/\+11:00$/)});
const target={articleId:'aaaaaaaaaaaaaaaaaaaaaaaa',collectionId:'bbbbbbbbbbbbbbbbbbbbbbbb',siteId:'cccccccccccccccccccccccc',articleTitle:TITLE};
function stub({draft=false,count=1,visibility='private'}={}){let writes=0;let text=`<h2>${TITLE}</h2><p>${SOURCE_URL}</p><p>These are ${count} listed upcoming departures.</p>`;return {get writes(){return writes},request:async(method,path,body)=>{if(path.startsWith('/collections'))return {collection:{id:target.collectionId,siteId:target.siteId,name:'Dive Travel',visibility}};if(method==='PUT'){writes++;text=body.text;return null}return {article:{id:target.articleId,collectionId:target.collectionId,name:TITLE,status:'published',hasDraft:draft,text}}}}}
test('publication checks identity, privacy and published readback',async()=>{const x=stub();const r=await updateTravelSnapshot(buildTravelSnapshot([row],at),target,null,{dryRun:false,request:x.request});assert.equal(r.status,'updated');assert.equal(x.writes,1)});
test('draft, public collection or drastic count drop cause zero writes',async()=>{for(const options of [{draft:true},{visibility:'public'},{count:10}]){const x=stub(options);await assert.rejects(updateTravelSnapshot(buildTravelSnapshot([row],at),target,null,{dryRun:false,request:x.request}));assert.equal(x.writes,0)}});
