import test from 'node:test';
import assert from 'node:assert/strict';
import {parseDate,parseTime,sydneyInstant,sydneyParts,bookingIdentity,parsePrice,buildSnapshot,renderArticle,validateCountChange,SOURCE_URL} from '../src/helpscout-beginner-snapshot.mjs';
const at='2026-10-02T05:36:57.830Z';
const url=(id,path='/charters/guided-shore-dives',title='Test dive')=>'https://www.abyss.com.au'+path+'?q='+Buffer.from('part_number='+title+'&date=&open_cart_id='+id).toString('base64');
const row=(id='1',path='/charters/guided-shore-dives',places='7')=>({cells:['','03 Oct 2026','03 Oct 2026','Guided Shore Dives','20',places,'$0.00',''],links:[{url:url(id,path)}],detail:['Start date: 03 Oct 2026 09:00 AM']});
const fixture=()=>({source:SOURCE_URL,finishedAt:at,errors:[],widgets:[{id:'widget3856',headers:['','','','Charter'],complete:true,rowCount:1,pages:[{rows:[row()]}]},{id:'widget3857',headers:['','','','Travel'],complete:true,rowCount:1,pages:[{rows:[row('2','/trips/forster')]}]}]});
test('date parser rejects impossible dates',()=>assert.throws(()=>parseDate('31 Feb 2026')));
test('date parser accepts leap day correctly',()=>assert.equal(parseDate('29 Feb 2028'),'2028-02-29'));
test('date parser rejects non-leap day',()=>assert.throws(()=>parseDate('29 Feb 2027')));
test('consistent 24-hour PM format normalises',()=>assert.equal(parseTime('16:30 PM'),'16:30'));
test('conflicting 24-hour AM format rejected',()=>assert.throws(()=>parseTime('16:30 AM')));
test('midnight/noon preserved',()=>{assert.equal(parseTime('12:00 AM'),'00:00');assert.equal(parseTime('12:00 PM'),'12:00');});
test('missing time stays unknown',()=>assert.equal(parseTime(''),null));
test('pre-DST Sydney conversion',()=>assert.equal(sydneyInstant('2026-10-03','08:00'),'2026-10-02T22:00:00.000Z'));
test('post-DST Sydney conversion',()=>assert.equal(sydneyInstant('2026-10-04','08:00'),'2026-10-03T21:00:00.000Z'));
test('spring gap rejected',()=>assert.throws(()=>sydneyInstant('2026-10-04','02:30')));
test('autumn ambiguous hour rejected',()=>assert.throws(()=>sydneyInstant('2027-04-04','02:30')));
test('Sydney date is not UTC date',()=>assert.equal(sydneyParts('2026-10-03T15:00:00Z').date,'2026-10-04'));
test('exact selected booking identity decoded',()=>assert.equal(bookingIdentity(url('123')).id,'123'));
test('external booking host rejected',()=>assert.throws(()=>bookingIdentity(url('123').replace('www.abyss.com.au','example.org'))));
test('booking credentials rejected',()=>assert.throws(()=>bookingIdentity(url('123').replace('https://','https://user@'))));
test('malformed booking parameter rejected',()=>assert.throws(()=>bookingIdentity('https://www.abyss.com.au/charters/boat-dives?q=bad')));
test('unknown price remains null, explicit zero retained',()=>{assert.equal(parsePrice(''),null);assert.equal(parsePrice('$0.00').amount,0);});
test('positive count never reaches output',()=>{const s=buildSnapshot(fixture());assert.equal(s.events[0].availability,'check_availability');assert.equal(s.events[0].availabilityLabel,'Check availability');assert.ok(!('availablePlaces' in s.events[0]));assert.ok(!renderArticle(s).includes('7 places'));});
test('zero is fully booked',()=>{const f=fixture();f.widgets[0].pages[0].rows[0].cells[5]='0';assert.equal(buildSnapshot(f).events[0].availability,'fully_booked');});
test('missing places are unknown, not zero',()=>{const f=fixture();f.widgets[0].pages[0].rows[0].cells[5]='';assert.equal(buildSnapshot(f).events[0].availability,'unknown');});
test('missing widget prevents complete snapshot',()=>{const f=fixture();f.widgets.pop();assert.throws(()=>buildSnapshot(f));});
test('incomplete pagination prevents publication',()=>{const f=fixture();f.widgets[0].complete=false;assert.throws(()=>buildSnapshot(f));});
test('row count mismatch rejected',()=>{const f=fixture();f.widgets[0].rowCount=2;assert.throws(()=>buildSnapshot(f));});
test('extraction error rejected',()=>{const f=fixture();f.errors.push({message:'bad page'});assert.throws(()=>buildSnapshot(f));});
test('duplicate booking rejected',()=>{const f=fixture();f.widgets[0].rowCount=2;f.widgets[0].pages[0].rows.push(row());assert.throws(()=>buildSnapshot(f));});
test('expiry uses elapsed 36h across DST',()=>{const f=fixture();f.finishedAt='2026-10-03T15:30:00Z';assert.equal(buildSnapshot(f).expiresAt,'2026-10-05T03:30:00.000Z');});
test('expired fixture rejected',()=>assert.throws(()=>buildSnapshot(fixture(),{now:'2026-10-03T17:36:57.830Z'})));
test('future check timestamp rejected',()=>assert.throws(()=>buildSnapshot(fixture(),{now:'2026-10-01T05:36:57.830Z'})));
test('travel date/time preserved without guessing zone',()=>{const f=fixture();const r=f.widgets[1].pages[0].rows[0];r.cells[2]='08 Oct 2026';const trip=buildSnapshot(f).events.find(e=>e.kind==='trip');assert.equal(trip.endDate,'2026-10-08');assert.equal(trip.startInstant,null);assert.match(trip.timeBasis,/confirm itinerary/);});
test('trip end before start rejected',()=>{const f=fixture();f.widgets[1].pages[0].rows[0].cells[2]='01 Oct 2026';assert.throws(()=>buildSnapshot(f));});
test('main/detail date disagreement rejected',()=>{const f=fixture();f.widgets[0].pages[0].rows[0].detail=['Start date: 04 Oct 2026 09:00 AM'];assert.throws(()=>buildSnapshot(f));});
test('unknown charter type fails closed',()=>{const f=fixture();f.widgets[0].pages[0].rows[0]=row('1','/charters/unknown');assert.throws(()=>buildSnapshot(f));});
test('social and freediving excluded explicitly',()=>{const f=fixture();f.widgets[0].pages[0].rows[0]=row('1','/charters/freedive-training');assert.equal(buildSnapshot(f).excluded[0].reason,'freediving');});
test('technical departure warning preserved',()=>{const f=fixture();f.widgets[0].pages[0].rows[0]=row('1','/charters/tech-boat-dives');assert.match(buildSnapshot(f).events[0].notes.join(' '),/Technical departure/);});
test('large count drop fails closed',()=>assert.throws(()=>validateCountChange({sourceCounts:{widget3856:10,widget3857:2}},{sourceCounts:{widget3856:72,widget3857:10}})));
test('normal count change accepted',()=>assert.doesNotThrow(()=>validateCountChange({sourceCounts:{widget3856:70,widget3857:10}},{sourceCounts:{widget3856:72,widget3857:10}})));
test('unverified empty source is not zero events',()=>{const f=fixture();f.widgets[0].pages=[];f.widgets[0].rowCount=0;assert.throws(()=>buildSnapshot(f));});
test('explicit verified empty category accepted',()=>{const f=fixture();f.widgets[0].pages=[];f.widgets[0].rowCount=0;f.widgets[0].explicitEmpty=true;assert.equal(buildSnapshot(f).counts.shore,0);});
test('escaped title cannot inject article HTML',()=>{const f=fixture();f.widgets[0].pages[0].rows[0].links=[{url:url('1','/charters/guided-shore-dives','<script>alert(1)</script>')}];assert.ok(!renderArticle(buildSnapshot(f)).includes('<script>'));});
