import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {DateTime} from 'luxon';
import {parseCalendar,buildCourseSnapshot,renderCourseSnapshot,publishCourseSnapshot,COLLECTION,TITLE,SLUG,comparable,schedulePlans} from '../src/helpscout-courses.mjs';
import {publishKnowledge} from '../src/helpscout-course-knowledge.mjs';
const raw=JSON.parse(await fs.readFile(new URL('./fixtures/course/rows.json',import.meta.url))),mapping=JSON.parse(await fs.readFile(new URL('../data/helpscout-course-mapping.json',import.meta.url))),now=DateTime.fromISO('2026-09-30T23:00:00+10:00'),make=(r=raw,p=null)=>buildCourseSnapshot(structuredClone(r),mapping,{now,previous:p});
test('complete current calendar spans both pages, retains languages and exact booking links',()=>{const s=make();assert.equal(s.sessions.length,95);assert.deepEqual(s.extraction.pageSizes,[50,45]);const chinese=s.sessions.find(x=>x.language==='Chinese');assert.ok(chinese.variant.includes('Chinese'));assert.equal(chinese.bookingUrl,raw.rows.find(r=>r.description===chinese.variant).bookingUrl);assert.ok(s.sessions.at(-1).endDate>'2027-04-02');});
test('server metadata, not defective JS offset default, establishes full range',async()=>{const x=parseCalendar(await fs.readFile(new URL('./fixtures/course/first-page.html',import.meta.url),'utf8'));assert.equal(x.total,95);assert.equal(x.totalPages,2);assert.equal(x.rows.length,50)});
test('reject duplicate, impossible date, changed course, price and capacity before publication',()=>{for(const patch of [{startDate:'31 Feb 2027'},{price:'$0.00'},{available:'99'},{name:'Unknown course'},{bookingUrl:'https://example.org/book'}]){const r=structuredClone(raw);Object.assign(r.rows[0],patch);assert.throws(()=>make(r));}const r=structuredClone(raw);r.rows.push(r.rows[0]);assert.throws(()=>make(r),/Duplicate/)});
test('source timetable discrepancies remain flagged rather than silently corrected',()=>{const s=make(),bad=s.sessions.filter(x=>x.bookingStatus==='date confirmation required');assert.ok(bad.length>0);assert.ok(bad.every(x=>x.warnings.length));assert.ok(s.sessions.some(x=>x.firstSessionDate<x.startDate));});
test('stale policy is 48 elapsed hours across Sydney DST',()=>{const r=buildCourseSnapshot(structuredClone(raw),mapping,{now:DateTime.fromISO('2026-10-03T02:30:00',{zone:'Australia/Sydney'})});assert.equal(DateTime.fromISO(r.staleAfter).diff(DateTime.fromISO(r.checkedAt),'hours').hours,48);assert.ok(r.staleAfter.endsWith('+11:00'));assert.ok(renderCourseSnapshot(r).includes('not real-time availability'));assert.ok(!renderCourseSnapshot(r).includes('Places left:'));});
test('suspicious disappearance preserves last snapshot by rejecting candidate',()=>{const p=make(),r=structuredClone(raw);r.rows=r.rows.slice(0,50);assert.throws(()=>make(r,p),/fell by more/)});
function docsMock(current=null){let articles=Array.isArray(current)?structuredClone(current):current?[current]:[],mutations=[];return {mutations,request:async(method,path,body)=>{if(method==='GET'&&path.startsWith('/collections/')&&path.includes('/articles'))return {articles:{items:articles,page:1,pages:1}};if(method==='GET'&&path.startsWith('/collections/'))return {collection:{id:COLLECTION,name:'Sydney Dive Courses',siteId:'6ab8b2dd4b37f75b5ff65b9c',visibility:'private'}};if(method==='GET'&&path==='/sites/6ab8b2dd4b37f75b5ff65b9c')return {site:{id:'6ab8b2dd4b37f75b5ff65b9c',title:'Dive course Doc'}};if(method==='GET'&&path.startsWith('/articles/'))return {article:articles.find(a=>a.id===path.split('/').at(-1))};mutations.push({method,path,body});if(method==='POST'){const article={...body,id:String(articles.length+1).padStart(24,'0'),hasDraft:false};articles.push(article);return article.id}if(method==='PUT'){const i=articles.findIndex(a=>a.id===path.split('/').at(-1));articles[i]={...articles[i],...body};return null}throw Error('Unexpected request')},get:()=>articles.find(a=>a.name===TITLE)}}
test('creates once, reads back, and skips duplicate Sydney local-day publication',async()=>{const s=make(),m=docsMock();const p=await publishCourseSnapshot(s,{request:m.request});assert.equal(p.status,'published-and-verified');assert.equal(comparable(m.get().text),comparable(schedulePlans(s).at(-1).text));await publishCourseSnapshot(s,{request:m.request});assert.equal(m.mutations.length,6);});
test('draft conflict prevents schedule overwrite',async()=>{const s=make(),m=docsMock({id:'123',name:TITLE,slug:SLUG,collectionId:COLLECTION,status:'published',hasDraft:true,text:renderCourseSnapshot(s)});await assert.rejects(publishCourseSnapshot(s,{request:m.request}),/draft conflict/);assert.equal(m.mutations.length,0)});
test('all twenty original knowledge identities retained and distinct subjects separated',async()=>{const p=JSON.parse(await fs.readFile(new URL('../data/helpscout-course-knowledge.json',import.meta.url)));assert.equal(p.articles.length,50);assert.equal(new Set(p.articles.filter(a=>a.id).map(a=>a.id)).size,20);for(const s of ['padi-nitrox-sydney','padi-peak-performance-buoyancy-sydney','padi-dry-suit-diver-sydney','padi-mermaid-sydney','emergency-first-response-sydney'])assert.ok(p.articles.some(a=>a.slug===s));assert.ok(!p.articles.some(a=>/CPR(?: and First Aid)? within (?:the (?:past|previous) )?12 months/i.test(a.text)));});

test('goal guide publishes into the new category with backup and readback',async()=>{const p=JSON.parse(await fs.readFile(new URL('../data/helpscout-course-knowledge.json',import.meta.url)));const existing=p.articles.slice(0,42).map((a,i)=>({...a,id:a.id||String(i+100).padStart(24,'0'),collectionId:COLLECTION,status:'published',hasDraft:false}));const guide=existing.find(a=>a.manageCategories);guide.categories=['6ab8b3eb7b6962906797d354'];const m=docsMock(existing);let backedUp=false;const request=async(method,path,body)=>{if(method!=='GET')assert.equal(backedUp,true);return m.request(method,path,body)};const result=await publishKnowledge({pack:p,request,saveBackup:async originals=>{assert.equal(originals.length,42);backedUp=true}});assert.equal(result.length,50);assert.deepEqual((await m.request('GET',`/articles/${guide.id}`)).article.categories,['6abd693c7cdaed3f1efa5777']);assert.equal(m.mutations.filter(x=>x.method==='POST').length,8);});
