import {load} from 'cheerio';
import {DateTime} from 'luxon';
import {createHash} from 'node:crypto';
import {makeDocsClient} from './helpscout-boat-bootstrap.mjs';
export {makeDocsClient};
export const SOURCE='https://www.abyss.com.au/avelo-course-beacon',COURSE='https://www.abyss.com.au/courses/avelo-dive-course',ZONE='Australia/Sydney',TITLE='Upcoming Avelo Course Dates — Updated Daily';
export const SITE='6abd977b7cdaed3f1efa58af',COLLECTION='6abd97aa535b0034271deb9a';
export const check=(v,m)=>{if(!v)throw Error(m)};
export const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const comparable=s=>String(s??'').replace(/<!--[\s\S]*?-->/g,'').replace(/>\s+</g,'><').trim();
export const hash=s=>createHash('sha256').update(s).digest('hex');
export const expiry=now=>now.setZone(ZONE).plus({days:1}).startOf('day').set({hour:7,minute:30}).toISO();
const mapping={
 '/courses/avelo-dive-course':{type:'recreational',names:['Avelo Dive Course'],article:'Avelo Dive Course and Avelo Essentials in Sydney'},
 '/courses/avelo-instructor-course-leading-edge-scuba-diving':{type:'instructor',names:['Avelo Instructor Course - Leading Edge Scuba Diving'],article:'Avelo Instructor training: current requirements'}
};
function parseDate(s){const d=DateTime.fromFormat(s,'dd LLL yyyy',{zone:ZONE,locale:'en'});check(d.isValid&&d.toFormat('dd LLL yyyy')===s,`Malformed Avelo date: ${s}`);return d.toISODate()}
export function parseRows(html){const $=load(`<table><tbody>${html}</tbody></table>`);return $('tr.main-row').toArray().map(r=>{const t=$(r).children('td').toArray().map(c=>clean($(c).text()));check(t.length===8,'Avelo row columns changed');const e=$(r).next('tr.expand-row');return {startDate:t[1],endDate:t[2],name:t[3],maxPlaces:t[4],available:t[5],price:t[6],bookingUrl:$(r).find('a[href]').attr('href'),description:clean(e.find('p[style]').text()),sessionDetails:e.find('p').toArray().map(p=>clean($(p).text())).filter(p=>!/^Our Price:/.test(p))}})}
export function parseCalendar(html){const $=load(html),scripts=$('script').text(),totalMatch=scripts.match(/var count = ["'](\d+)["']/),pagesMatch=scripts.match(/var totalPages = parseInt\(["'](\d+)["']\)/),colIds=scripts.match(/var col_ids = ["']([\d,]+)["']/)?.[1],groupId=scripts.match(/'group_id':\s*["']([\d,]+)["']/)?.[1];
 check(totalMatch&&pagesMatch&&colIds&&groupId,'Avelo pagination metadata missing');const total=Number(totalMatch[1]),pages=Number(pagesMatch[1]);check(pages===Math.ceil(total/50)||(total===0&&pages===1),'Inconsistent Avelo pagination');check(pages<=100,'Avelo pagination limit exceeded');
 const headings=$('thead th').toArray().map(e=>clean($(e).text())).filter(Boolean);check(JSON.stringify(headings)===JSON.stringify(['Start date','End date','Course','Max. Places','Places Available','Price']),'Avelo headings changed');return {total,pages,colIds,groupId,rows:parseRows($('tbody').html()??'')};}
export async function scrapeAvelo(fetchImpl=fetch){
 const get=async(url,data)=>{const r=await fetchImpl(url,{...(data?{method:'POST',body:new URLSearchParams(data)}:{}),headers:{'X-Requested-With':'XMLHttpRequest',Referer:SOURCE},signal:AbortSignal.timeout(45000),redirect:'error'});check(r.ok,`Avelo source HTTP ${r.status}`);const t=await r.text();check(!/verify you are human|access denied|forbidden access|checking your browser/i.test(t),'Avelo source blocked request');return t};
 const shell=load(await get(SOURCE));check(shell('#widget4869 widget[data-id="4869"]').length===1,'Avelo feed widget identity changed');
 const widget=load(await get('https://www.abyss.com.au/ajax/getwidget',{sw_id:'4869'})),w=widget('course_group_calendar');check(w.length===1&&w.attr('data-id')==='40518,40519','Avelo widget product groups changed');
 const meta=parseCalendar(await get('https://www.abyss.com.au/ajax/course_group_calendar',{title:w.attr('data-title'),parent_id:w.parent().attr('id'),group_id:w.attr('data-id'),offset:'50'}));
 const rows=[...meta.rows],pageSizes=[rows.length];check(rows.length===Math.min(50,meta.total),'Incomplete Avelo first page');
 for(let page=2;page<=meta.pages;page++){const batch=parseRows(await get('https://www.abyss.com.au/ajax/ajax_course_group_calendar',{page:String(page),group_id:meta.groupId,col_ids:meta.colIds,offset:'50'}));check(batch.length===Math.min(50,meta.total-(page-1)*50),`Incomplete Avelo page ${page}`);rows.push(...batch);pageSizes.push(batch.length)}
 check(rows.length===meta.total,'Incomplete Avelo extraction');return {rows,extraction:{sourceTotal:meta.total,pages:meta.pages,pageSizes,widget:'4869',groups:'40518,40519'}};
}
export function buildSnapshot(raw,{now=DateTime.now(),previous=null}={}){
 const local=now.setZone(ZONE),seen=new Set();const rows=raw.rows.map(r=>{
 const startDate=parseDate(r.startDate),endDate=parseDate(r.endDate);check(startDate<=endDate,'Avelo end date precedes start');check(DateTime.fromISO(endDate).diff(DateTime.fromISO(startDate),'days').days<=60,'Suspicious Avelo duration');
 let u;try{u=new URL(r.bookingUrl)}catch{throw Error('Malformed Avelo booking URL')};check(u.origin==='https://www.abyss.com.au'&&mapping[u.pathname]&&u.searchParams.has('q'),'Unmapped Avelo product or booking URL');
 const m=mapping[u.pathname];check(m.names.includes(r.name),`Unmapped Avelo course name: ${r.name}`);check(!/odyssey|private|chinese|中文|french|german|japanese/i.test(r.description),'Unmapped Avelo package or language variant');
 const code=new URLSearchParams(Buffer.from(u.searchParams.get('q'),'base64').toString('utf8')),id=code.get('open_cart_id'),partNumber=code.get('part_number');check(/^\d+$/.test(id??'')&&partNumber,'Avelo event identity missing');check(!seen.has(id),`Duplicate Avelo event ${id}`);seen.add(id);
 check(/^\$[\d,]+\.\d{2}$/.test(r.price),'Malformed Avelo price');const price=Number(r.price.replace(/[$,]/g,''));check(price>=50&&price<=20000,'Suspicious Avelo price');const old=previous?.prices?.[id];check(!old||price/old>=.75&&price/old<=1.25,'Avelo price changed by more than 25%; review required');
 check(/^\d+$/.test(r.maxPlaces),'Avelo capacity missing');const capacity=Number(r.maxPlaces);check(capacity>0&&capacity<=100,'Invalid Avelo capacity');
 const rawAvailability=clean(r.available)||'Not supplied';let places=null,status='availability unknown';
 if(/^\d+$/.test(rawAvailability)){places=Number(rawAvailability);check(places<=capacity,'Avelo places exceed capacity');status=places===0?'sold out at check':'listed with places at check'}
 else if(/^(sold out|full)$/i.test(rawAvailability))status='sold out at check';else if(/waitlist/i.test(rawAvailability))status='waitlist — confirm with Abyss';else if(/enquir|contact/i.test(rawAvailability))status='enquiry required';else check(!/^-\d+|^\d+[.,]/.test(rawAvailability),'Malformed Avelo availability');
 const first=r.sessionDetails.find(x=>x.startsWith('Start date:')),match=first?.match(/^Start date: (\d{2} [A-Za-z]{3} \d{4}) (\d{1,2}):(\d{2}) (AM|PM)$/);let warnings=[];
 if(first){check(match,'Malformed Avelo session date');check(Number(match[2])>=1&&Number(match[2])<=12&&Number(match[3])<60,'Malformed Avelo session time');check(parseDate(match[1])===startDate,'Avelo source session does not match listed start')}
 return {id,partNumber,courseType:m.type,courseArticle:m.article,course:r.name,variant:r.description,language:'Not specified by source',startDate,endDate,sessionDetails:r.sessionDetails,rawAvailability,places,capacity,status,price,currency:'AUD',bookingUrl:r.bookingUrl,warnings};
 }).filter(r=>r.startDate>=local.toISODate()).sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.course.localeCompare(b.course)||a.id.localeCompare(b.id));
 if(previous?.futureCount>1)check(rows.length>=previous.futureCount*.5,'Avelo row count fell by more than 50%; review required');
 return {version:1,parserVersion:'avelo-1',checkedAt:local.toISO(),validUntil:expiry(local),localDate:local.toISODate(),source:SOURCE,extraction:raw.extraction,rows};
}
export async function validateLinks(snapshot,fetchImpl=fetch){
 for(const r of snapshot.rows){const response=await fetchImpl(r.bookingUrl,{redirect:'follow',signal:AbortSignal.timeout(45000)});check(response.ok,`Avelo booking HTTP ${response.status}`);const u=new URL(response.url),original=new URL(r.bookingUrl);check(u.origin===original.origin&&u.pathname===original.pathname&&u.searchParams.get('q')===original.searchParams.get('q'),'Avelo booking redirect lost selected event');const html=await response.text(),$=load(html);check(!/verify you are human|access denied|checking your browser/i.test(html),'Avelo booking blocked');
 check(html.includes(r.id)&&html.includes(r.partNumber),'Selected Avelo booking identity not present');$('script,style,noscript').remove();const text=clean($('body').text());const date=DateTime.fromISO(r.startDate,{zone:ZONE}).toFormat('LLL d, yyyy');check(text.includes(date),'Selected Avelo date not present on booking page');check(text.includes('Add to Cart')||text.includes('Contact us for booking'),'Avelo booking controls missing');
 const starts=text.match(/Starts\s*:\s*(.*?)(?=Add to Cart|Description|Additional Information)/i)?.[1];check(starts&&starts.includes(date)&&starts.includes(r.course),'Selected Avelo event heading mismatch');
 const price=starts.match(/Price:\s*\$([\d,]+\.\d{2})/i);check(price&&Number(price[1].replace(/,/g,''))===r.price,'Avelo booking price differs from feed');
 r.selectedSessionDetails=clean(starts).replace(/\b\d+ Left!\s*/g,'').slice(0,1400);r.linkCheckedAt=snapshot.checkedAt;
 }
 return snapshot;
}
export function renderSnapshot(s){const e=escape,fmt=d=>DateTime.fromISO(d,{zone:ZONE}).toFormat('cccc d LLLL yyyy');let html=`<!-- ABYSS_AVELO_SNAPSHOT_V1 --><h2>Current Avelo course dates</h2><p><strong>Status: ${s.rows.length?'VERIFIED CURRENT':'NO FUTURE COURSES LISTED'}.</strong> Last successful check: ${e(s.checkedAt)}. Valid until: ${e(s.validUntil)}. Timezone: Australia/Sydney. Scheduled refresh: 7:00 am daily.</p><p>Coverage: all ${s.extraction.sourceTotal} source rows across ${s.extraction.pages} pages; ${s.rows.length} future listings. ${s.rows.length?'Future start range: '+e(fmt(s.rows[0].startDate))+' to '+e(fmt(s.rows.at(-1).startDate))+'.':'The feed returned a verified zero-result future schedule.'}</p><p>These are listed dates, prices and availability from the last check, not live inventory. Confirm the current price and places on the selected booking page. Do not make scarcity claims from seat counts. Use only this dedicated Avelo snapshot for Avelo recommendations; the general 48-hour course rule does not extend its valid-until time.</p><h2>Choosing and booking</h2><p>For a direct date question, give the earliest matching current date and its exact link promptly; offer up to three matching options when helpful. Check all sessions and the exact course type. Do not substitute a recreational course for an instructor intake or Odyssey package. Unknown availability is not confirmed availability. Do not recommend sold-out, conflicted or past rows as ready to book. If the current time is beyond valid-until, or freshness cannot be verified, use <a href="${COURSE}">the live Avelo course page</a> without asserting dates, prices or places. An enquiry is not a reservation.</p>`;
 for(const r of s.rows){html+=`<h2>${e(r.course)} — ${e(fmt(r.startDate))}</h2><p>Course type: ${e(r.courseType)}. Match requirements using ${e(r.courseArticle)}. Package: ${e(r.variant)}. Language: ${e(r.language)}. Start: ${e(r.startDate)}. End: ${e(r.endDate)}.</p><p>Listed price: AUD $${r.price.toFixed(2)}. Listed status: ${e(r.status)}. Raw availability at check: ${e(r.rawAvailability)}. This count is not real-time availability.</p><p>Session details supplied by the listing: ${e(r.sessionDetails.join(' | '))}. Selected booking details: ${e(r.selectedSessionDetails??'Not supplied')}.</p><p><a href="${e(r.bookingUrl)}">Check ${e(r.course)} on ${e(fmt(r.startDate))} and confirm live places</a></p>`}
 html+=`<h2>No matching Avelo date</h2><p>If no date fits, use <a href="${COURSE}">the live Avelo course page</a> or <a href="https://www.abyss.com.au/contact-us">ask the Avelo team</a> with the diver’s preferred dates. No instructor or Odyssey row means no verified intake in this snapshot, not that those programmes are discontinued.</p>`;return html;}
export function staleHtml(reason='The current daily schedule has not been verified.') {return `<!-- ABYSS_AVELO_SNAPSHOT_V1 --><h2>Current Avelo dates need a live check</h2><p><strong>Status: STALE OR UNVERIFIED.</strong> ${escape(reason)} Do not assert dates, prices, availability or seat counts from any earlier snapshot.</p><p><a href="${COURSE}">Check the live Avelo course page</a> for the current selected date and places, or <a href="https://www.abyss.com.au/contact-us">ask the Avelo team about your preferred dates</a>. An enquiry does not reserve a place.</p>`}
async function listArticles(request){let result=[];for(let page=1;page<=20;page++){const a=(await request('GET',`/collections/${COLLECTION}/articles?pageSize=100&status=all&page=${page}`)).articles;check(a&&Array.isArray(a.items)&&a.page===page&&Number.isInteger(a.pages),'Invalid Avelo Docs pagination');result.push(...a.items);if(page>=a.pages)return result}throw Error('Avelo Docs pagination limit')}
export async function validateTarget(request){const c=(await request('GET',`/collections/${COLLECTION}`)).collection;check(c?.id===COLLECTION&&c.siteId===SITE&&c.name==='Avelo Diving'&&c.visibility==='private','Avelo collection identity/privacy mismatch');const site=(await request('GET',`/sites/${SITE}`)).site;check(site?.id===SITE,'Avelo site identity mismatch');return c}
export function resolvePack(pack,coursePack){check(pack.siteId===SITE&&pack.collectionId===COLLECTION&&pack.articles.length===14,'Invalid Avelo pack');const names=new Set(),slugs=new Set();return pack.articles.map(a=>{let r=a;if(a.sharedCourseArticleId){const shared=coursePack.articles.find(x=>x.id===a.sharedCourseArticleId);check(shared,'Shared Avelo source missing');r={name:shared.name,slug:a.slug,text:shared.text,keywords:shared.keywords,sharedCourseArticleId:a.sharedCourseArticleId}}check(!names.has(r.name)&&!slugs.has(r.slug),'Duplicate Avelo pack article');names.add(r.name);slugs.add(r.slug);check(r.text&&r.keywords.length>=5,'Incomplete Avelo knowledge article');const links=[...r.text.matchAll(/href="([^"]+)"/g)].map(m=>new URL(m[1]));check(links.every(u=>u.origin==='https://www.abyss.com.au'),'Non-Abyss customer link in Avelo knowledge');return r})}
export async function publishKnowledge({request,articles,previous=null,saveBackup}){
 await validateTarget(request);const refs=await listArticles(request),existing=[];for(const x of refs)existing.push((await request('GET',`/articles/${x.id}`)).article);
 const plans=articles.map(a=>{const matches=existing.filter(x=>x.name===a.name||x.slug===a.slug);check(matches.length<=1,'Duplicate Avelo destination');const current=matches[0];if(current){check(current.name===a.name&&current.slug===a.slug&&current.collectionId===COLLECTION&&current.status==='published'&&!current.hasDraft,'Avelo destination conflict');const old=previous?.articles?.find(x=>x.id===current.id);if(!a.schedule&&old)check(hash(comparable(current.text))===old.textHash,'Avelo article edited since managed publication');}return {a,current}});
 await saveBackup(existing);const result=[];for(const {a,current} of plans){let id=current?.id;const text=a.schedule&&current?current.text:a.text;if(current&&!a.schedule&&comparable(current.text)!==comparable(text)){const fresh=(await request('GET',`/articles/${id}`)).article;check(!fresh.hasDraft&&comparable(fresh.text)===comparable(current.text),'Concurrent Avelo article edit');await request('PUT',`/articles/${id}`,{name:a.name,text,keywords:a.keywords})}else if(!id)id=await request('POST','/articles',{collectionId:COLLECTION,status:'published',name:a.name,slug:a.slug,text,keywords:a.keywords});
 const read=(await request('GET',`/articles/${id}`)).article;check(read.collectionId===COLLECTION&&read.status==='published'&&read.name===a.name&&read.slug===a.slug&&comparable(read.text)===comparable(text),'Avelo article readback mismatch');check(a.keywords.every(k=>(read.keywords||[]).includes(k)),'Avelo keyword readback mismatch');result.push({id,name:a.name,slug:a.slug,schedule:!!a.schedule,textHash:hash(comparable(read.text))});}
 return result;
}
export async function publishSnapshot({request,id,text}){await validateTarget(request);const current=(await request('GET',`/articles/${id}`)).article;check(current?.collectionId===COLLECTION&&current.name===TITLE&&current.status==='published'&&!current.hasDraft&&current.text.includes('ABYSS_AVELO_SNAPSHOT_V1'),'Avelo schedule identity/status mismatch');if(comparable(current.text)!==comparable(text))await request('PUT',`/articles/${id}`,{text});const verified=(await request('GET',`/articles/${id}`)).article;check(verified.name===TITLE&&verified.collectionId===COLLECTION&&comparable(verified.text)===comparable(text),'Avelo schedule readback mismatch');return {articleId:id,status:'published-and-read-back',textHash:hash(comparable(text))};}
