import {load} from 'cheerio';
import {DateTime} from 'luxon';
import {createHash} from 'node:crypto';
import {makeDocsClient} from './helpscout-boat-bootstrap.mjs';
export const SOURCE_URL='https://www.abyss.com.au/course-beacon',ZONE='Australia/Sydney',COLLECTION='6ab8b33984f08c58bb03f7e6',TITLE='Upcoming Sydney Course Dates — Updated Daily',SLUG='upcoming-sydney-course-dates-updated-daily';
export const check=(ok,msg)=>{if(!ok)throw new Error(msg)};
export const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const comparable=s=>String(s??'').replace(/<!--[\s\S]*?-->/g,'').replace(/>\s+</g,'><').trim();
export const hash=s=>createHash('sha256').update(s).digest('hex');
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
export function parseDate(s){const d=DateTime.fromFormat(s,'dd LLL yyyy',{zone:ZONE,locale:'en'});check(d.isValid&&d.toFormat('dd LLL yyyy')===s,`Malformed calendar date: ${s}`);return d.toISODate()}
export function parseRows(html){const $=load(`<table><tbody>${html}</tbody></table>`);return $('tr.main-row').toArray().map(r=>{const t=$(r).children('td').toArray().map(c=>clean($(c).text()));check(t.length===8,'Course row columns changed');const e=$(r).next('tr.expand-row');return {startDate:t[1],endDate:t[2],name:t[3],maxPlaces:t[4],available:t[5],price:t[6],bookingUrl:$(r).find('a[href]').attr('href'),description:clean(e.find('p[style]').text()),sessionDetails:e.find('p').toArray().map(p=>clean($(p).text())).filter(p=>!/^Our Price:/.test(p))}})}
export function parseCalendar(html){const $=load(html),s=$('script').text();const total=Number(s.match(/var count = ["'](\d+)["']/)?.[1]),totalPages=Number(s.match(/var totalPages = parseInt\(["'](\d+)["']\)/)?.[1]);const colIds=s.match(/var col_ids = ["']([\d,]+)["']/)?.[1],groupId=s.match(/'group_id':\s*["'](\d+)["']/)?.[1];check(total>0&&totalPages===Math.ceil(total/50)&&colIds&&groupId,'Calendar pagination metadata missing or inconsistent');const headings=$('thead th').toArray().map(e=>clean($(e).text())).filter(Boolean);check(JSON.stringify(headings)===JSON.stringify(['Start date','End date','Course','Max. Places','Places Available','Price']),'Calendar headings changed');return {total,totalPages,colIds,groupId,rows:parseRows($('tbody').html())}}
export async function scrapeCourses(fetchImpl=fetch){
 const get=async(url,data)=>{const r=await fetchImpl(url,{...(data?{method:'POST',body:new URLSearchParams(data)}:{}),headers:{'X-Requested-With':'XMLHttpRequest',Referer:SOURCE_URL},signal:AbortSignal.timeout(45000),redirect:'error'});check(r.ok,`Course source HTTP ${r.status}`);const t=await r.text();check(!/verify you are human|access denied|forbidden access|checking your browser/i.test(t),'Course source blocked the request');return t};
 const shell=load(await get(SOURCE_URL));check(shell('#widget4866 widget[data-id="4866"]').length===1,'Course widget identity changed');
 const widget=load(await get('https://www.abyss.com.au/ajax/getwidget',{sw_id:'4866'})),w=widget('course_group_calendar');check(w.length===1,'Course widget configuration missing');
 const first=await get('https://www.abyss.com.au/ajax/course_group_calendar',{title:w.attr('data-title'),parent_id:w.parent().attr('id'),group_id:w.attr('data-id'),offset:'50'}),meta=parseCalendar(first);
 check(meta.totalPages<=100,'Calendar page limit exceeded');const rows=[...meta.rows],pageSizes=[rows.length];check(rows.length===Math.min(50,meta.total),'Incomplete first course page');
 for(let page=2;page<=meta.totalPages;page++){const html=await get('https://www.abyss.com.au/ajax/ajax_course_group_calendar',{page:String(page),group_id:meta.groupId,col_ids:meta.colIds,offset:'50'}),batch=parseRows(html);check(batch.length===Math.min(50,meta.total-(page-1)*50),`Incomplete course page ${page}`);rows.push(...batch);pageSizes.push(batch.length)}
 check(rows.length===meta.total,'Extracted count differs from source total');return {rows,extraction:{sourceTotal:meta.total,pageSizes,pages:meta.totalPages,method:'DS360 course-beacon widget and its own paginated AJAX endpoint; explicit offset 50'}};
}
export function buildCourseSnapshot(raw,mapping,{now=DateTime.now(),previous=null}={}){
 const checked=now.setZone(ZONE),seen=new Set(),sessions=raw.rows.map(r=>{
 const startDate=parseDate(r.startDate),endDate=parseDate(r.endDate);check(startDate<=endDate,'Course ends before it starts');check(DateTime.fromISO(endDate).diff(DateTime.fromISO(startDate),'days').days<=370,'Suspicious course duration');
 let u;try{u=new URL(r.bookingUrl)}catch{throw Error('Malformed booking link')};check(u.origin==='https://www.abyss.com.au'&&u.pathname.startsWith('/courses/')&&u.searchParams.has('q'),'Unexpected booking URL');
 const code=new URLSearchParams(Buffer.from(u.searchParams.get('q'),'base64').toString('utf8')),id=code.get('open_cart_id');check(/^\d+$/.test(id??'')&&code.get('part_number'),'Missing selected booking identifiers');check(!seen.has(id),`Duplicate course booking ${id}`);seen.add(id);
 const match=mapping[u.pathname];check(match,`Unmapped course: ${u.pathname}`);check(match.names.includes(r.name),`Unmapped course name: ${r.name}`);
 const price=Number(r.price.replace(/[$,]/g,''));check(/^\$[\d,]+\.\d{2}$/.test(r.price)&&price>=5&&price<=20000,`Suspicious course price for ${r.name}`);
 check(/^\d+$/.test(r.maxPlaces)&&/^\d+$/.test(r.available),'Malformed capacity');const capacity=Number(r.maxPlaces),available=Number(r.available);check(capacity>0&&capacity<=100&&available<=capacity,'Invalid course capacity');
 const prev=previous?.sessions?.find(s=>s.id===id);check(!prev||price/prev.price<=2&&price/prev.price>=.5,`Course price changed by more than 2x: ${r.name}`);
 const firstSessionRaw=r.sessionDetails.find(x=>x.startsWith('Start date:'));let firstSessionDate=null,firstSessionTime=null,warnings=[];
 if(firstSessionRaw){const m=firstSessionRaw.match(/^Start date: (\d{2} [A-Za-z]{3} \d{4}) (\d{1,2}):(\d{2}) (AM|PM)$/);check(m,`Malformed source session: ${firstSessionRaw}`);firstSessionDate=parseDate(m[1]);let h=Number(m[2]),mi=Number(m[3]);check(h<=23&&mi<60&&!(h>12&&m[4]==='AM'),'Malformed session time');if(h<12&&m[4]==='PM')h+=12;if(h===12&&m[4]==='AM')h=0;firstSessionTime=`${String(h).padStart(2,'0')}:${String(mi).padStart(2,'0')}`;if(firstSessionDate>endDate)warnings.push('The source first-session date falls after the listed course end date. Ask Abyss to confirm before booking.');if(firstSessionDate<startDate)warnings.push('The source lists an earlier session/preparation date; confirm the full timetable before booking.');}
 return {id,courseKey:match.key,articleSlug:match.articleSlug,course:match.title,listingName:r.name,variant:r.description,language:/\bChinese\b/i.test(r.description)?'Chinese':'Not specified by source',startDate,endDate,firstSessionDate,firstSessionTime,sessionDetails:r.sessionDetails,price,currency:'AUD',available,capacity,bookingStatus:available===0?'sold out at check':warnings.length?'date confirmation required':'listed with places at check',bookingUrl:r.bookingUrl,warnings};
 }).filter(r=>r.startDate>=checked.toISODate()).sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.course.localeCompare(b.course)||a.id.localeCompare(b.id));
 check(sessions.length>0,'No future courses extracted');if(previous?.sessions){const remaining=previous.sessions.filter(s=>s.startDate>=checked.toISODate());check(sessions.length>=remaining.length*.75,'Course count fell by more than 25%; review before publishing');}
 return {version:1,checkedAt:checked.toISO(),localDate:checked.toISODate(),staleAfter:checked.plus({hours:48}).toISO(),source:SOURCE_URL,extraction:raw.extraction,sessions};
}
export async function validateBookingLinks(snapshot,fetchImpl=fetch){
 const pending=[...snapshot.sessions],failures=[];
 await Promise.all(Array.from({length:4},async()=>{while(pending.length){const s=pending.shift();try{const r=await fetchImpl(s.bookingUrl,{signal:AbortSignal.timeout(45000),redirect:'follow'});check(r.ok,`HTTP ${r.status}`);const u=new URL(r.url),body=await r.text();check(u.origin==='https://www.abyss.com.au'&&u.pathname.startsWith('/courses/'),'Unexpected redirect');check(!/access denied|forbidden access|verify you are human/i.test(body),'Blocked course link');check(body.includes(s.id),'Selected booking ID absent from course page');check(body.includes('Add to Cart')||body.includes('Contact us')||body.includes('contact_us'),'Booking controls missing');s.linkCheckedAt=snapshot.checkedAt;}catch(e){failures.push(`${s.id}: ${e.message}`)}}}));check(!failures.length,`Broken or unverified booking links: ${failures.join('; ')}`);
}
export function renderCourseSnapshot(s){
 const e=escape,fmt=d=>DateTime.fromISO(d,{zone:ZONE}).toFormat('ccc d LLL yyyy'),groups=Map.groupBy(s.sessions,r=>r.course);
 let html=`<!-- ABYSS_COURSE_SNAPSHOT_V1 --><h2>${TITLE}</h2><p><strong>Last successful check: ${e(s.checkedAt)} (Australia/Sydney).</strong> Scheduled daily at 2:30 am Sydney time. This is a snapshot, not real-time availability.</p><p><strong>Stale after: ${e(s.staleAfter)}.</strong> After this time, or if the check time cannot be verified, do not assert dates, prices or availability from this article. Use <a href="${SOURCE_URL}">live course listings</a> instead.</p><p>Coverage: ${s.sessions.length} future course listings; source total ${s.extraction.sourceTotal} across ${s.extraction.pages} pages. First start ${e(fmt(s.sessions[0].startDate))}; latest listed end ${e(fmt(s.sessions.reduce((d,r)=>r.endDate>d?r.endDate:d,'')))}. Courses absent from this snapshot may be arranged by enquiry.</p><h2>How to recommend a date</h2><p>First match the diver’s goal and prerequisites using the focused course article. Offer one to three suitable dates, preserving the exact package and language. Do not infer English delivery when the source is unspecified. Do not recommend sold-out or date-conflicted entries as available. Confirm preparation and every session, especially when an earlier session is listed. Never claim “only two places left” from this snapshot. Current price, places and inclusions are confirmed on the selected live booking page. For Nitrox, optional ocean dives cost extra under the course description; the session label alone does not establish that they are included.</p>`;
 for(const [course,rows] of groups){html+=`<h2>${e(course)}</h2>`;for(const r of rows){html+=`<h3>${e(fmt(r.startDate))}${r.endDate!==r.startDate?' – '+e(fmt(r.endDate)):''}</h3><p><strong>Course:</strong> ${e(r.course)}. <strong>Variant:</strong> ${e(r.variant)}. <strong>Language:</strong> ${e(r.language)}. <strong>Listed price:</strong> AUD $${r.price.toFixed(2)}. <strong>Status:</strong> ${e(r.bookingStatus)}.</p><p><strong>Source session information:</strong> ${e(r.sessionDetails.join(' | '))}. Confirm the full timetable on the live page.</p>${r.warnings.length?'<p><strong>Timetable check:</strong> '+e(r.warnings.join(' '))+'</p>':''}<p><a href="${e(r.bookingUrl)}">${r.warnings.length?'Review the source timetable and ask Abyss to confirm':'Check this '+e(r.course)+' date and book'}</a></p>`}}
 return html;
}
export async function listArticles(request){const all=[];for(let page=1;page<=50;page++){const x=(await request('GET',`/collections/${COLLECTION}/articles?pageSize=100&status=all&page=${page}`)).articles;check(Array.isArray(x?.items)&&x.page===page&&Number.isInteger(x.pages),'Invalid Docs pagination');all.push(...x.items);if(page>=x.pages)return all;}throw Error('Docs pagination overflow')}
export async function validateCollection(request){const c=(await request('GET',`/collections/${COLLECTION}`)).collection;check(c?.id===COLLECTION&&c.name==='Sydney Dive Courses'&&['private','public'].includes(c.visibility),'Course collection identity mismatch');const site=(await request('GET',`/sites/${c.siteId}`)).site;check(site?.name==='Dive course Doc','Course Docs site mismatch');return c}
export async function publishCourseSnapshot(snapshot,{request}={}){
 const html=renderCourseSnapshot(snapshot);await validateCollection(request);const matches=(await listArticles(request)).filter(a=>a.slug===SLUG||a.name===TITLE);check(matches.length<=1,'Duplicate course schedule articles');let id=matches[0]?.id,current=id?(await request('GET',`/articles/${id}`)).article:null;
 if(current){check(current.collectionId===COLLECTION&&current.status==='published'&&!current.hasDraft,'Schedule identity/status/draft conflict');check(current.name===TITLE&&(current.text.includes('ABYSS_COURSE_SNAPSHOT_V1')||current.text.includes('Last successful check:')),'Unmanaged schedule body');const last=current.text.match(/Last successful check:\s*(\d{4}-\d{2}-\d{2}T[^\s<]+)/)?.[1];if(last&&DateTime.fromISO(last).setZone(ZONE).toISODate()===snapshot.localDate)return {status:'already-published-today',id};}
 if(!id)id=await request('POST','/articles',{collectionId:COLLECTION,status:'published',slug:SLUG,name:TITLE,text:html,categories:['6ab8b3eb7b6962906797d354'],keywords:['Sydney course dates','upcoming dive courses','course bookings','updated daily']});else await request('PUT',`/articles/${id}`,{text:html});
 const read=(await request('GET',`/articles/${id}`)).article;check(read.status==='published'&&read.collectionId===COLLECTION&&comparable(read.text)===comparable(html),'Published course snapshot readback mismatch');return {status:'published-and-verified',id,count:snapshot.sessions.length};
}
export {makeDocsClient};
